ROUTES = {
    "平静": "neutral",
    "中性": "neutral",
    "正常": "neutral",
    "叙述": "neutral",
    "neutral": "neutral",
    "温柔": "gentle",
    "安慰": "gentle",
    "宠溺": "gentle",
    "暖": "gentle",
    "gentle": "gentle",
    "生气": "angry",
    "愤怒": "angry",
    "压怒": "angry",
    "质问": "angry",
    "angry": "angry",
    "悲伤": "sad",
    "难过": "sad",
    "失落": "sad",
    "哽咽": "sad",
    "sad": "sad",
    "惊恐": "panic",
    "慌张": "panic",
    "害怕": "panic",
    "紧张": "panic",
    "panic": "panic",
    "耳语": "whisper",
    "低声": "whisper",
    "悄悄": "whisper",
    "气声": "whisper",
    "whisper": "whisper",
}
INSTRUCTIONS = {
    "neutral": "自然生活化对白，语气克制，停连随语义变化，不要播音腔，不要机械匀速",
    "gentle": "轻声安慰，语速稍慢，呼吸自然，句尾放松，不要刻意煽情",
    "angry": "压住怒气，咬字稍有力度，节奏有变化，不要持续喊叫",
    "sad": "克制失落，气息稍弱，允许自然停顿，不要哭腔过满",
    "panic": "紧张急促但吐字清楚，呼吸略乱，不要尖叫",
    "whisper": "近距离低声说话，气声自然，保持清晰，不要全句虚声",
}
